export const products = [
  {
    id: 1,
    image: "nu1.png",
    title: "Giftset Burberry Goddess EDP 3Pcs",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Burberry/ Nhóm hương:	Hương Thơm Ngát - Aromatic/ Phong cách:	Quyến rũ - nữ tính - sang trọng ",
    price: 5115000,
    unit: "VNĐ",
  },
  {
    id: 2,
    image: "nu2.png",
    title: "Giftset Marc Jacobs Perfect EDP 3Pcs",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Marc Jacobs/ Nhóm hương:	Hương Hoa Cỏ - Floral/ Phong cách:	Năng động, quyến rũ, phá cách",
    price: 3578000,
    unit: "VNĐ",
  },
  {
    id: 3,
    image: "nu3.png",
    title: "Giftset Gucci Guilty Pour Homme EDP 3pcs",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Gucci/ Nhóm hương:	Hương Gỗ Cay Nồng - Woody Spicy/ Phong cách:	Ngọt ngào, Gợi cảm, Mãnh liệt",
    price: 4876000,
    unit: "VNĐ",
  },
  {
    id: 4,
    image: "nu4.png",
    title: "Giftset Lancôme Idôle EDP 3PCS",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Lancôme/ Nhóm hương:	Hương Hoa cỏ Síp - Chypre Floral/ Phong cách:	Tươi mới, Thanh lịch, Tinh tế",
    price: 2185000,
    unit: "VNĐ",
  },
  {
    id: 5,
    image: "nu5.png",
    title: "Nước hoa YSL Libre EDP Holiday",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Yves Saint Laurent",
    price: 4797000,
    unit: "VNĐ",
  },
  {
    id: 6,
    image: "nam1.png",
    title: "Nước hoa Yves Saint Laurent MYSLF EDP",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Yves Saint Laurent",
    price: 4227000,
    unit: "VNĐ",
  },
  {
    id: 7,
    image: "nam2.png",
    title: "Nước hoa Dolce&Gabbana The One Gold Pour Homme EDP Intense",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Dolce & Gabbana",
    price: 4200000,
    unit: "VNĐ",
  },
  {
    id: 8,
    image: "nam3.png",
    title: "Nước hoa Calvin Klein Men's Eternity Aromatic Essence EDP",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Calvin Klein",
    price: 3050000,
    unit: "VNĐ",
  },
  {
    id: 9,
    image: "nam4.png",
    title: "Nước hoa Mcm Onyx EDP",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	MCM",
    price: 1690000,
    unit: "VNĐ",
  },
  {
    id: 10,
    image: "nam5.png",
    title: "Nước hoa YSL La Nuit de L’Homme EDT",
    size: ["Full Size", "Mini" , "Tester", "Vial"],
    description: "Nhãn hiệu:	Yves Saint Laurent",
    price: 4009000,
    unit: "VNĐ",
  },
];
